stages:
  process_data:
    cmd: python scripts/process_data.py data/raw_data data/processed_data/dataset.pkl
    deps:
      - scripts/process_data.py
      - data/raw_data
    params:
      - process_data.review_text_column
      - process_data.cols_to_delete
    outs:
      - data/processed_data/dataset.pkl

  split_data:
    cmd: python scripts/split_data.py data/processed_data/dataset.pkl data/train_test_data params.yaml
    deps:
      - scripts/split_data.py
      - data/processed_data/dataset.pkl
    params:
      - split_data.test_size
      - split_data.stratify
      - split_data.label_column
    outs:
      - data/train_test_data/train.pkl
      - data/train_test_data/test.pkl

  eval_model:
    cmd: python scripts/eval_model.py data/train_test_data params.yaml metrics.json
    deps:
      - scripts/eval_model.py
      - data/train_test_data/train.pkl
      - data/train_test_data/test.pkl
    params:
      - model.strategy
    metrics:
      - metrics.json:
          cache: false
