split_data:
  test_size: 0.2
  stratify: True
  label_column: LABEL-rating

model:
  strategy: uniform

process_data:
  review_text_column: review_text
  cols_to_delete:
    - product_id
    - brand_id
    - variation_type
    - variation_value
    - variation_desc
    - author_id
    - submission_time
    - skin_tone
    - eye_color
    - skin_type
    - hair_color
    - product_id
